---
- name: Install node.js (npm plus all dependencies)
  yum: name=npm state=present enablerepo=epel

- name: Instlal forever module (to run node.js app)
  npm: name={{ item }} global=yes state=present
  with_items: "{{ node_npm_modules }}"