---
- name: Ensure drupal directory exists.
  file:
    path: "{{ drupal_core_path }}"
    state: directory
    owner: www-data
    group: www-data

- name: Check if drupal project already exists.
  stat:
    path: "{{ drupal_core_path }}/composer.json"
  register: drupal_composer_json

- name: Create drupal project.
  composer:
    command: create-project
    arguments: drupal/recommended-project "{{ drupal_core_path }}"
    working_dir: "{{ drupal_core_path }}"
    no_dev: true
  become_user: www-data
  when: not drupal_composer_json.stat.exists

- name: Add drush to the drupal site with composer.
  composer:
    command: require
    arguments: drush/drush:10.*
    working_dir: "{{ drupal_core_path }}"
  become_user: www-data
  when: not drupal_composer_json.stat.exists

- name: Install drupal.
  command: >
    vendor/bin/drush si -y --site-name="{{ drupal_site_name }}"
    --account-name=admin
    --account-pass=admin
    --db-url=mysql://{{ domain }}:1234@localhost/{{ domain }}
    --root={{ drupal_core_path }}/web
    chdir={{ drupal_core_path }}
    creates={{ drupal_core_path }}/web/sites/default/settings.php
  notify: restart apache
  become_user: www-data