---
- name: Check if Drupal project already exists.
  stat:
    path: "{{ drupal_core_path }}/composer.json"
  register: drupal_composer_json
  
- name: Add drush to the drupal site with Composer.
  composer:
    command: require
    arguments: drush/drush:10.*
    working_dir: "{{ drupal_core_path }}"
  become_user: www-data
  when: not drupal_composer_json.stat.exists
