---
ssh_key: ansible
image_os: ami-03d315ad33b9d49c4
subnet_id: subnet-04ca8bfe54103ddb3
boto_version: default
aws_region: us-east-1
build_type: t2.micro

security_group:
  - name: gluster-sg
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 2049
        to_port: 2049
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 38465
        to_port: 38465
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 38466
        to_port: 38466
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 38467
        to_port: 38467
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 49152
        to_port: 49152
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 49153
        to_port: 49153
        cidr_ip: 0.0.0.0/0
      - proto: udp
        from_port: 111
        to_port: 111
        cidr_ip: 0.0.0.0/0

instances:
  - name: gluster1
    group:
      - gluster
    security_group:
      - gluster-sg
    private_address: 172.31.23.2

  - name: gluster2
    group:
      - gluster
    security_group:
      - gluster-sg
    private_address: 172.31.23.3
