node('master') {
  stage('Starting pipeline') {
    echo 'Starting pipeline'
    emailext body: "Build #${env.BUILD_NUMBER} has started",
      to: 'thomas.vu.it@gmail.com',
      subject: "Jenkins: ${JOB_NAME}"
  }

  stage('Pull from SCM') {
    echo 'Pull from SCM'
    git 'https://github.com/typ-ex/ansible-for-devops-in-aws'
  }

  try {
    dir('chapter 9/ELK') {
      stage('Debug incoming code') {
        echo 'Debug incoming code'
        sh "yamllint ."
      }

      stage('Build') {
        echo 'Build'
        sh "ansible-playbook provision.yml"
      }

      stage('Ensure dependencies are installed') {
        echo 'Ensure dependencies are installed'
        sh "ansible-galaxy install -r requirements.yml"
      }

      stage('Ensure playbook will run okay') {
        sh "ansible-playbook main.yml --syntax-check"
      }

      stage('Provision ELK stack') {
        echo 'Provision ELK stack'
        sh "ansible-playbook elk/main.yml"
      }

      stage('Provision web stack') {
        echo 'Provision web stack'
        sh "ansible-playbook web/main.yml"
      }
    }
  }
  catch(err) {
    currentBuild.result = 'FAILURE'
    throw err
    }
  finally {
    echo 'Sending results email'
    emailext attachLog: true, body: "Build #${env.BUILD_NUMBER}: ${currentBuild.result}\nAttached is the build log",
      to: 'thomas.vu.it@gmail.com',
      subject: "Jenkins: ${JOB_NAME}"
  }
}