node('master') {
  stage('Pull from SCM') {
    git 'https://github.com/typ-ex/ansible-for-devops-in-aws.git'
  }

  stage('Where am I?') {
    sh "ls -a"
  }

  stage('Change to the appropriate directory') {
    sh "cd 'Chapter 4'/CentOS-Nodejs"
  }

  stage('Ensure setup can debug code') {
    sh "ansible-playbook setup.yml"
  }

  stage('Debugging submitted code') {
    sh "yamllint ."
    sh "ansible-playbook main.yml --syntax-check"
    sh "ansible-lint main.yml"
  }

  stage('Build') {
    sh "ansible-playbook provision.yml"
  }

  stage('Provision') {
    sh "ansible-playbook configure.yml"
  }
}