node('master') {
  stage('Starting pipeline') {
    mail bcc: '', body: "Build #${env.BUILD_NUMBER} has started", cc: '', from: 'do not reply', replyTo: 'donotreply@madeupjenkinsserver.net', subject: "${env.BUILD_TAG}", to: 'thomas.vu.it@gmail.com'
  }
  
  stage('Pull from SCM') {
    git 'https://github.com/typ-ex/ansible-for-devops-in-aws'
  }

  dir('Chapter 6/roles node') {
    stage('Debug submitted code') {
      sh "yamllint ."
      sh "ansible-playbook main.yml --syntax-check"
      sh "ansible-lint main.yml"
    }

    stage('Build') {
      sh "ansible-playbook provision.yml"
    }

    stage('Deploy') {
      sh "ansible-playbook configure.yml"
    }
  }
}