---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/aws.yml

  tasks:
    - name: configure EC2 instance
      ec2:
        key_name: "{{ ssh_key }}"
        instance_tags:
          Name: "{{ item.name }}"
          inventory_group: "{{ item.group }}"
          inventory_host: "{{ item.name }}"
        group: "{{ item.security_group }}"
        instance_type: "{{ build_type }}"
        image: "{{ image_os }}"
        private_ip: "{{ item.private_address }}"
        vpc_subnet_id: "{{ subnet_id }}"
        wait: true
        wait_timeout: 500
        exact_count: 1
        count_tag:
          inventory_host: "{{ item.name }}"
        profile: "{{ boto_version }}"
        region: "{{ aws_region }}"
      with_items: "{{ instance }}"

- hosts: all
  gather_facts: false

  tasks:
    - name: Everything is up and visible via ssh
      wait_for_connection:
