---
- hosts: rails
  become: true

  vars_files:
    - vars/rails.yml

  roles:
    - geerlingguy.git
    - geerlingguy.nodejs
    - geerlingguy.ruby
    - geerlingguy.passenger

  tasks:
    - name: Server is up and visible via ssh
      wait_for_connection:

    - name: Install app dependencies
      apt:
        name:
          - libsqlite3-dev
          - libreadline-dev
          - tzdata
        state: present

    - name: Ensure app directory exists and is writeable
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0755
