---
- name: Firewall configuration.
  hosts: deployments
  become: yes

  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - geerlingguy.firewall

- name: HA Proxy load balancer security_group
  hosts: balancer
  become: yes

  vars:
    haproxy_backend_servers:
      - name: 172.31.4.2
        address: 172.31.4.2:80
      - name: 172.31.4.3
        address: 172.31.4.3:80

  roles:
    - geerlingguy.haproxy

- name: Apache webserver setup
  hosts: app
  become: yes

  roles:
    - geerlingguy.apache